# Generated by Django 5.2.1 on 2025-05-15 18:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='id_product',
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'id_product')},
        ),
    ]
